
spring:
  application:
    name: User-Service
#here need to tell where to get configuration 
  config:
    import: optional:configserver:http://localhost:8090
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/